auto: true
server: true
pygments: true
permalink: none
baseurl: "contribute/"
oauth_client_id: b0b021a756dfce6d31bc
gatekeeper_url: http://project-open-data.herokuapp.com
exclude:
- .gitignore
- README.md
- node_modules
- package.json
- Gruntfile.coffee
rootUrl: project-open-data/project-open-data.github.io
